instruct_model:
  id: "dify-app"
  api_base: "http://192.168.2.110:8888/v1"
  api_key: "app-3159QQoxdYd6yIsbkO6df9TV"
  name: "Dify 对话应用"
thinking_model:
  id: "dify-app"
  api_base: "http://192.168.2.110:8888/v1"
  api_key: "app-3159QQoxdYd6yIsbkO6df9TV"
  name: "Dify 对话应用（思考模式）"
fast_model:
  id: "dify-app"
  api_base: "http://192.168.2.110:8888/v1"
  api_key: "app-3159QQoxdYd6yIsbkO6df9TV"
  name: "Dify 对话应用（快速模式）"
visual_model:
  id: "Qwen/Qwen3-VL-235B-A22B-Instruct"
  api_base: "https://api-inference.modelscope.cn/v1"
  api_key: "ms-b7f877a2-4d7d-4846-8576-e7aec9b40388"
  name: "通义千问3-235B-视觉"
embedding_model:
  id: "Qwen/Qwen3-Embedding-8B"
  api_base: "https://api-inference.modelscope.cn/v1"
  api_key: "ms-b7f877a2-4d7d-4846-8576-e7aec9b40388"
  name: "通义千问3-8B-嵌入"
reranker_model:
  id: "Qwen/Qwen3-Reranker-8B"
  api_base: "https://api-inference.modelscope.cn/v1"
  api_key: "ms-b7f877a2-4d7d-4846-8576-e7aec9b40388"
  name: "通义千问3-8B-排序"
